#!/bin/bash
unset checkPID_GEN
checkPID_GEN=$(ps x|grep -v grep|grep "8888")
[[ ! $checkPID_GEN ]] && PID_GEN='[ ❌ ]' || PID_GEN='[ ✅ ]'
[[ -e /etc/systemd/system/btkill.service ]] && kkid="✅" || kkid="❌"

menu_src () {
#namcli=$(bash /etc/ADM-db/BotGen.sh | grep  message_from_first_name | grep message_from_first_name | grep -i message_from_first_name | awk {'print $4'})
#${message_text[$usuario]}  $message_from_first_name $message_from_last_name
[[ -z ${callback_query_from_username} ]] && nUSER=${message_from_username} || nUSER=${callback_query_from_username}
bot_retorno="◢▆█▆██◢ ${botname} ◣██▆█▆◣\n"
	 if [[ $(echo $permited|grep "${chatuser}") = "" ]]; then
		 if [[ $(cat ${CID}|grep "${chatuser}") = "" ]]; then
		 [[ -e /root/RegBOT/banID ]] && idBAN=$(cat /root/RegBOT/banID) || idBAN=""
		 #[[ -z "$(echo $idBAN | grep "${chatuser")" ]] && {
#		 	 bot_retorno+="$line\n"
			 #bot_retorno+="𝙃𝙤𝙡𝙖 (  $message_from_first_name $message_from_last_name  ), 𝘽𝙞𝙚𝙣𝙫𝙚𝙣𝙞𝙙𝙤 𝙖𝙡 𝙈𝙚𝙣𝙪"
			 bot_retorno+="$line\n"
			 bot_retorno+="  ❌| 𝙉𝙊 𝘾𝙐𝙀𝙉𝙏𝘼𝙎 𝘾𝙊𝙉 𝘼𝘾𝘾𝙀𝙎𝙊  |❌"
			 bot_retorno+="$line\n"
			 bot_retorno+="💎 @${nUSER} 𝐬𝐨𝐥𝐢𝐜𝐢𝐭𝐚 𝐭𝐮 𝐚𝐜𝐜𝐞𝐬𝐨💎 \n"
			 bot_retorno+="$line\n"
			 bot_retorno+="/ID	| 𝐦𝐮𝐞𝐬𝐭𝐫𝐚 𝐭𝐮 𝐈𝐃 📍\n"
			 bot_retorno+="/menu	| 𝐜𝐨𝐦𝐚𝐧𝐝𝐨𝐬 📍\n"
			 bot_retorno+="/ayuda	| 𝐞𝐱𝐩𝐥𝐢𝐜𝐚𝐜𝐢𝐨𝐧 𝐝𝐞 𝐮𝐬𝐨 📍\n"
			 bot_retorno+="/price	| 𝐩𝐫𝐞𝐜𝐢𝐨𝐬 𝐝𝐞𝐥 𝐛𝐨𝐭 📍\n"
			 bot_retorno+="/chekid	| 𝐯𝐞𝐫𝐢𝐟𝐢𝐜𝐚𝐫 𝐈𝐃 𝐥𝐮𝐞𝐠𝐨 𝐝𝐞 𝐩𝐚𝐠𝐨 📍\n"
			 bot_retorno+="$line\n"
			 bot_retorno+="𝔸𝔻ℚ𝕌𝕀𝔼ℝ𝔼 𝕋𝕌 𝕄𝔼𝕄𝔹ℝ𝔼𝕊𝕀𝔸 ℙ𝔸ℝ𝔸 𝕌𝕊𝔸ℝ 𝔼𝕊𝕋𝔼 𝔹𝕆𝕋.\n ℂ𝕠𝕟𝕥𝕒𝕔𝕥𝕖 𝕒 @$(cat < /etc/ADM-db/resell)\n"
			 bot_retorno+="$line\n"
			 menu_printSN
		#	 } || {
		#	 bot_retorno+="$line\n"
		#	 bot_retorno+="     🚫🚫️ SU ID FUE BANEADO 🚫🚫 \n"
		#	 bot_retorno+="$line\n"
		#	 menu_printSN
		#	 }
			 #msj_fun
		 else
		 	[[ -e /etc/menu_ito ]] && nomkey="$(cat /etc/menu_ito)" || nomkey="$(curl -sSL "https://www.dropbox.com/s/z38hj1mz3q9krso/menu_credito")"
		 	numkey_used=$(grep -o -i $message_chat_id /etc/gerar-sh-log | wc -l)
			numkey_gen=$(grep -o -i $message_chat_id /etc/ADM-db/num-key.cont | wc -l)
			data_user=$(cat ${CID}|grep "${chatuser}" | awk -F "|" '{print $2}')
			data_sec=$(date +%s)
			data_user_sec=$(date +%s --date="$data_user")
			variavel_soma=$(($data_user_sec - $data_sec))
			dias_use=$(($variavel_soma / 86400))
			[[ "$dias_use" -le 0 ]] && dias_use=0 || dias_use=$(($dias_use + 1))
			bot_retorno+="$line\n"
#			 bot_retorno+="  ⚠️ ACCESO ILIMITADO POR『 $dias_use 』DIAS ⚠️ \n  ✓ INCLUIDO TU RESELLER EN LA KEY ✔"
#			 bot_retorno+=" ✩ ID AUTORIZADO HASTA EL $data_user | $(date +%R) ⌚\n"
			 [[ -z $checkPID_GEN ]] && bot_retorno+=" ⚠️ ADVERTENCIA!! BotGen ⚠️\n" || bot_retorno+=" ✩ BotGen FUNCIONANDO ONLINE 🔥\n"
			 [[ -z ${callback_query_from_first_name} ]] && firsnme="${message_from_first_name}" || firsnme="${callback_query_from_first_name}"
			 [[ -z ${callback_query_from_last_name} ]] && lastnme="${message_from_last_name}" || lastnme="${callback_query_from_last_name}"
			 bot_retorno+="$line\n"
			 bot_retorno+=" RESELLER ACTUAL : ${firsnme} ${lastnme}\n"
			 bot_retorno+="$line\n"
			 bot_retorno+="/menu\n"
			 #bot_retorno+="/hack	► 	HACKEAR LA NASA :v \n"
			 bot_retorno+="/rvntas	► 	𝙖𝙜𝙧𝙚𝙜𝙖𝙧 𝙧𝙚𝙫𝙚𝙣𝙙𝙚𝙙𝙤𝙧. 👥 \n"
			 bot_retorno+="💎/instal        ➩       𝙫𝙚𝙧 𝙞𝙣𝙨𝙩𝙖𝙡𝙖𝙙𝙤𝙧 𝙤𝙛𝙞𝙘𝙞𝙖𝙡.\n"
			 bot_retorno+="🔑/keygen	➩	𝙜𝙚𝙣𝙚𝙧𝙖𝙧 𝙠𝙚𝙮🔑\n"
#			 bot_retorno+="/ayuda   ►  Ayuda/Instrucciones del BOT |\n"
#			 bot_retorno+=" ❊ 𝚁𝚎𝚌𝚞𝚎𝚛𝚍𝚊 𝙲𝚘𝚕𝚊𝚋𝚘𝚛𝚊𝚛 💸💰 , 𝚜𝚒 𝚝𝚎 𝚊𝚐𝚛𝚊𝚍𝚘 𝚖𝚒 𝚃𝚛𝚊𝚋𝚊𝚓𝚘 ❊\n"
#			 bot_retorno+="Si tienes inconvenientes con el Bot  🎁 Contactame : +$(cat < /etc/numctc) 📲\n"
			 bot_retorno+=" 🔐 『 $numkey_used 』𝙆𝙚𝙮𝙨 𝙐𝙨𝙖𝙙𝙖𝙨 🔓,『 $numkey_gen 』𝙆𝙚𝙮𝙨 𝙂𝙚𝙣𝙚𝙧𝙖𝙙𝙖𝙨 🗝️ \n"
			 bot_retorno+="$line\n"
			 menu_print
		 fi
		 
	 else
		 unset usadas
		 usadas="$(cat /etc/http-instas)"
		 [[ ! $usadas ]] && k_used="0" || k_used="$usadas"
		 bot_retorno+="$line\n𝔾𝔼ℕ: $PID_GEN 			┊ 𝕂𝕖𝕪𝕤 𝕌𝕊𝔼𝔻: [$k_used]\n"
		 bot_retorno+="𝕀ℙ: $(wget -qO- ipv4.icanhazip.com)	┊ $(printf '%(%D)T') | $(printf '%(%H:%M:%S)T') \n"
		 bot_retorno+="$line\n"
		 bot_retorno+="🖥️/infosys	➩ 	𝙙𝙚𝙩𝙖𝙡𝙡𝙚𝙨 𝙨𝙤𝙗𝙧𝙚 𝙩𝙪 𝙑𝙋𝙎.🖥 \n"
		 bot_retorno+="${kkid}/killid	➩ 	𝙡𝙞𝙢𝙞𝙩𝙖𝙙𝙤𝙧 𝙙𝙚 𝙘𝙖𝙙𝙪𝙘𝙞𝙙𝙖𝙙. ${kkid}\n"
		 bot_retorno+="📋/idgen	➩ 	𝙡𝙞𝙨𝙩𝙖 𝙞𝙙 𝙖𝙘𝙩𝙞𝙫𝙤𝙨. 📋\n"
		 bot_retorno+="💬/chat	➩ 	𝙘𝙝𝙖𝙩𝙚𝙖𝙧 𝙘𝙤𝙣 𝙚𝙡 𝙗𝙤𝙩. 💬\n"
		 bot_retorno+="🔍/buscar	➩ 	𝙗𝙪𝙨𝙘𝙖𝙧 𝙞𝙙. 🔍\n"
		 bot_retorno+="💎/instal	➩ 	𝙫𝙚𝙧 𝙞𝙣𝙨𝙩𝙖𝙡𝙖𝙙𝙤𝙧 𝙤𝙛𝙞𝙘𝙞𝙖𝙡. 💎 \n"
		 #bot_retorno+="/hack	➩ 	HACKEAR LA NASA :v \n"
		 bot_retorno+="👥/addrev	➩ 	𝙖𝙜𝙧𝙚𝙜𝙖𝙧 𝙧𝙚𝙫𝙚𝙣𝙙𝙚𝙙𝙤𝙧. 👥 \n"
		 bot_retorno+="📍/ayuda	➩	𝙚𝙭𝙥𝙡𝙞𝙘𝙖𝙘𝙞𝙤𝙣 𝙘𝙤𝙢𝙖𝙣𝙙𝙤𝙨.📍 \n"
		 bot_retorno+="🗑️/cache	➩	𝙡𝙞𝙢𝙥𝙞𝙖𝙧 𝙫𝙥𝙨. 🗑️ \n"
		 bot_retorno+="🤖/update	➩	𝙖𝙘𝙩𝙪𝙖𝙡𝙞𝙯𝙖𝙧 𝙗𝙤𝙩. 🤖  \n"
		 bot_retorno+="⚠️/reboot	➩	𝙧𝙚𝙞𝙣𝙞𝙘𝙞𝙖𝙧 𝙫𝙥𝙨. ⚠️ \n"
		 bot_retorno+="💲/price   ➩ 𝙥𝙧𝙚𝙘𝙞𝙤𝙨 𝙙𝙚𝙡 𝙗𝙤𝙩.💲\n"
		 bot_retorno+="😎/donar	➩ 𝙢𝙨𝙟 𝙥𝙞𝙙𝙞𝙚𝙣𝙙𝙤 𝙙𝙤𝙣𝙖𝙘𝙞𝙤𝙣.😎 \n"
		 bot_retorno+="$line\n"
		 menu_print
	 fi	
}
